//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
/// <summary>
/// This class make costam
/// </summary>
public class Class1 : MyClass
{
	/// <summary>
	/// This method use RSA with server d
	/// </summary>
	/// <param name="a"> Interface Message</param>
	public void CheckValue(int a)
	{
		RSACryptoServiceProvider d;
		d.PersistKeyInCsp(d);
	}
}

