// <auto-generated />
namespace RejestrFaktur.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlatnoscTyp_WalutaPoprawki : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlatnoscTyp_WalutaPoprawki));
        
        string IMigrationMetadata.Id
        {
            get { return "201512092231361_PlatnoscTyp_WalutaPoprawki"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
